# @package _global_
# this config just has the nadir tracks for observations 

paths:
    #l96: /Odyssey/public/l96_dataset/L96_truth_obs_mask_boc2010.nc
    l96_dir: /Odyssey/public/l96_dataset/
    l96_trajectories_train: 
      - ${paths.l96_dir}/L96_truth_obs_mask_boc2010_single_traj_1.nc
      - ${paths.l96_dir}/L96_truth_obs_mask_boc2010_single_traj_2.nc
      - ${paths.l96_dir}/L96_truth_obs_mask_boc2010_single_traj_3.nc
      - ${paths.l96_dir}/L96_truth_obs_mask_boc2010_single_traj_4.nc

    l96_trajectories_test: 
      - ${paths.l96_dir}/L96_truth_obs_mask_boc2010_single_traj_6.nc

domain: ???


trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 50
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 3
      filename: '{val_mse:.5f}-{epoch:03d}'

datamodule:
  _target_: contrib.L96.data.MultiTrajDataModule
  input_das: 
    _target_: contrib.L96.utils.load_l96_data_multi
    paths: ${paths.l96_trajectories_train} 
  domains:
    train:
      time: {_target_: builtins.slice, _args_: [20000, 80000]}
    val: 
      time: {_target_: builtins.slice, _args_: [11000, 19000]}
    test: 
      time: {_target_: builtins.slice,  _args_: [1000, 10000]}
  xrds_kw:
    patch_dims: { time: 200, lat: 40, lon: 1}
    strides: { time: 50, lat: 40, lon: 1}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 32, num_workers: 1}


model:
  _target_: contrib.QG.models.Lit4dVarNetIgnoreNaN
  w_mse: 50.
  w_grad_mse: 0.0
  w_prior: 1. #1.
  w_mse_lr: 0.
  w_grad_mse_lr: 0
  osse_with_interp_error: false #true
  persist_rw: False
  opt_fn:
    _target_: ocean4dvarnet.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
  rec_weight:
      _target_: contrib.L96.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 0, lon: 0}
      offset: 0
  solver:
    _target_: contrib.QG.models.GradSolver_withStep #GradSolver_FM #GradSolver_withStep # # # # # ##GradSolver_FM # #ocean4dvarnet.models.GradSolver
    n_step: 5 #2 #5 #10
    lr_grad: 0. #1e3
    std_init: 0.1
    input_grad_update: 'obs+state' #'subgrad+state' #'obs+state' ##'grad-only' #'grad+state' #'obs-only'  # 'grad+previous'  #'gobs+sgprior' #'grad+state'  #'grad-only' #'grad+state'  #'grad+state' #    
    # lr_grad: 0.2  
    prior_cost:
      _target_: contrib.QG.models.GenericAEPriorCost
      model_ae:
        _target_: contrib.QG.unet_circular.UNetModelCircular
        dims: 2
        in_channels: 1 #${datamodule.xrds_kw.patch_dims.time}
        out_channels: 1 #${datamodule.xrds_kw.patch_dims.time}
        model_channels: 32 #32
        num_res_blocks: 2
        channel_mult: [1,2,4]
        attention_resolutions: []
        use_checkpoint: true
        dropout: 0.1
        bias: false #true #
        #interp_mode: 'bilinear' #'nearest' # 
      #_target_: contrib.4dvarnet_latent.models.AEPriorCostOneScale #AEPriorCostTwoScale #BilinAEPriorCostTwoScale # 
      #dim_in: 15 #15 #${datamodule.xrds_kw.train.patch_dims.time}+${model.solver.latent_decoder.dim_latent}
      #dim_hidden: 128 #128 #64
      #bilin_quad: false
      # bilin_quad: true
      #downsamp: 4 #4 #null # 4
      #bias: false
    obs_cost:
      _target_: ocean4dvarnet.models.BaseObsCost
    grad_mod:
      _target_: contrib.QG.models.GradModelWithCondition
      #use_grad_norm: true
      grad_model: 
        _target_: contrib.QG.unet_circular.UNetModel2Circular
        dims: 2
        in_channels: 2 #${datamodule.xrds_kw.patch_dims.time}
        out_channels: 1 #${datamodule.xrds_kw.patch_dims.time}
        model_channels: 64 #32
        num_res_blocks: 2
        channel_mult: [1,2,4]
        attention_resolutions: []
        use_checkpoint: true
        dropout: 0.1
        bias: false #true #
        interp_mode: 'bilinear' #'nearest' # 

      
  test_metrics: ${metrics.test_metrics}
  pre_metric_fn: 
        _target_: xarray.Dataset.isel
        _partial_: True
        time: {_target_: builtins.slice, _args_: [1000, 10000]}
        lat: ${domain.test.lat}
        lon: ${domain.test.lon}

metrics:
  nrmse_scores: {_target_: src.utils.rmse_based_scores_from_ds, _partial_: True}
  psd_scores: {_target_: src.utils.psd_based_scores_from_ds, _partial_: True}
  get0: {_target_: operator.itemgetter, _args_: [0]}
  get1: {_target_: operator.itemgetter, _args_: [1]}
  test_metrics:
    'mu': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get0}']}
    'sig': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get1}']}
    'lx': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get0}']}
    'lt': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get1}']}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: ocean4dvarnet.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}

defaults:
  - /domain: qg_sim_128
  - _self_

